# Numpy

In [1]:
#para importar la libreria
import numpy as np

#otra forma de importar sin utilizar np, es hacer
# from numpy import *

#pero esto crea confusion con funciones de otras librerias


In [2]:
L1 = [1,2,3,4,5,6,7,8,9]

#Creamos np desde una lista
N_1 = np.array(L1)
N_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#Se puede cambiar el tipo de dato, por ejemplo
N_2 = np.array(L1, dtype='float32')
N_2

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

los tipos son

- bool_
- int_ , intc, intp (indexar) , int8, int16, int32, int64
- uint8,.... (son enteros sin signos)
- float_ (media precision),float32(normal), float64(precision)
- complex_ (equiv a 16),complex64 (32), complex128 (64) , una parte es imaginaria y otra real

# Crear matrices

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(3,12,dtype="float64")

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [8]:
# por pasos de un tamaño dado parecido a a:b:c

np.arange(3,12,0.1)

array([ 3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,
        4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,
        5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,
        6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,
        7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,
        8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,
        9.6,  9.7,  9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6,
       10.7, 10.8, 10.9, 11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7,
       11.8, 11.9])

In [9]:
 # para dar determinado numero de pasos en un intervalo, NOTA: este si incluye hasta el ultimo aunque se puede modificar con parametros
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [10]:
# matriz identidad tamaño n
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Redimensionar 

In [11]:
x=np.zeros((8,3))
x


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
x.reshape((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
x  #conserva forma

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
xs=np.arange(24)

In [17]:
xs.reshape((3,8))  

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
xs   #no modifica la forma original de xs

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
# para aplanar, otra forma de crear matriz, se supone que altera original
matriz = np.array([[1,2,3,4],[5,6,7,8]])
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
np.ravel(matriz)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
matriz  # pero no paso nada

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
#es igual pero una copia de la matriz, supuestamente
matriz.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
#transponer
np.transpose(matriz)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [25]:
matriz #sigue sin afectar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
#redimensionar, crea con dimension especifica, como le faltan en el siguiente caso, rellena repitiendo
np.resize(matriz,(5,2))


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [1, 2]])

In [28]:
matriz   #por lo visto na

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# ejercicios

In [3]:
np.arange(5,121)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [4]:
M_1 = np.arange(0,16)
M_2 = np.resize(M_1,(4,4))
M_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
#prueba alternativa
np.resize(np.arange(0,16),(4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [7]:
 np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [8]:
np.linspace(1,5,20).reshape((5,4))

array([[1.        , 1.21052632, 1.42105263, 1.63157895],
       [1.84210526, 2.05263158, 2.26315789, 2.47368421],
       [2.68421053, 2.89473684, 3.10526316, 3.31578947],
       [3.52631579, 3.73684211, 3.94736842, 4.15789474],
       [4.36842105, 4.57894737, 4.78947368, 5.        ]])