# funciones universales (ufunc)

funciones que se realizan sobre todos y cada elemento de un array sin usar un bucle for

## funciones unarias
elemento a elemento : sqrt, sin, cos , **2, + , -

se pueden crear muchas



In [4]:
import numpy as np

x = np.arange(10)

In [3]:
print(x+3)
x-3

[ 3  4  5  6  7  8  9 10 11 12]


array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [4]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [5]:
alpha = np.linspace(0, 2*np.pi, 4)

In [6]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [7]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [8]:
#funciones exponenciales
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [9]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [10]:
np.power(3,x)  #equiv a 3^x

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [11]:
np.power(x,3)  #equiv a x^3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [12]:
np.log(alpha)  # error porque hay numero 0 en alpha

/tmp/ipykernel_28131/2175199034.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(alpha)  # error porque hay numero 0 en alpha


array([      -inf, 0.73926478, 1.43241196, 1.83787707])

In [13]:
np.log10(alpha)

/tmp/ipykernel_28131/4206049137.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(alpha)


array([      -inf, 0.32105861, 0.62208861, 0.79817987])

## funciones binarias
Binarias: se ralizan como en matemáticas 

In [15]:
#valores desconocidos
np.nansum(alpha)

12.566370614359172

In [16]:
#version si nan
np.sum(alpha)

12.566370614359172

In [17]:
np.max(alpha)

6.283185307179586

In [18]:
np.var(alpha)

5.483113556160754

In [19]:
np.median(alpha)

3.141592653589793

In [20]:
np.std(alpha)

2.3416049103469088

In [21]:
np.argmin(x)  #posicion del numero mas pequeño

0

In [22]:
np.argmax(x)  #posicion del numero mas grande

9

## con booleanos

In [24]:
y=np.array([True,False, False, True])

In [25]:
#al algun true?
np.any(y)

True

In [26]:
#todos?
np.all(y)

False

# funciones por dimensiones



In [6]:
# generar valores aleatorios entre 0 y 1
z=np.random.rand(3,5)
z

array([[0.16501311, 0.48360088, 0.68359307, 0.82032078, 0.31433263],
       [0.61463879, 0.60995105, 0.67882129, 0.10089668, 0.76494139],
       [0.28508584, 0.94911706, 0.21815399, 0.96713372, 0.06574138]])

In [7]:
z.sum()

7.721341650094281

In [8]:
z.sum(axis=0)  #por columnas axis 0

array([1.06473773, 2.04266899, 1.58056835, 1.88835118, 1.1450154 ])

In [9]:
z.sum(axis=1)  #por filas axis 1

array([2.46686046, 2.7692492 , 2.48523198])

In [10]:
#ejemplo dimension 3, es como si se corrieran, por ejemplo antes axis 0 sera axis 1, el 1 sera 2, y el cero sera propiamente la
#dimension más "superficial"

z=np.random.rand(3,5,3)
z

array([[[0.16835939, 0.58558991, 0.50808019],
        [0.29730254, 0.60933723, 0.52861179],
        [0.4472141 , 0.46125195, 0.17463062],
        [0.80804242, 0.667099  , 0.32215352],
        [0.1990835 , 0.59310502, 0.71421365]],

       [[0.01107267, 0.84556596, 0.26255542],
        [0.42663659, 0.63805456, 0.49837532],
        [0.47050994, 0.93584117, 0.96841341],
        [0.65113916, 0.49233799, 0.44594234],
        [0.08079271, 0.02901154, 0.25611287]],

       [[0.36761443, 0.09008266, 0.52049269],
        [0.33292955, 0.24666374, 0.13757237],
        [0.79938147, 0.30483044, 0.06896216],
        [0.84800354, 0.25707513, 0.85548728],
        [0.76734575, 0.03714675, 0.10588192]]])

In [11]:
#dimension 2 seria 
z.sum(axis=0)

array([[0.54704649, 1.52123852, 1.2911283 ],
       [1.05686868, 1.49405554, 1.16455948],
       [1.71710551, 1.70192355, 1.21200619],
       [2.30718512, 1.41651213, 1.62358314],
       [1.04722197, 0.65926331, 1.07620845]])

In [12]:
z.sum(axis=1)

array([[1.92000195, 2.91638311, 2.24768977],
       [1.64015107, 2.94081123, 2.43139937],
       [3.11527475, 0.93579872, 1.68839642]])

In [13]:
z.sum(axis=2)  

array([[1.26202948, 1.43525157, 1.08309667, 1.79729493, 1.50640218],
       [1.11919405, 1.56306647, 2.37476452, 1.5894195 , 0.36591713],
       [0.97818978, 0.71716566, 1.17317407, 1.96056595, 0.91037442]])

In [15]:
# verificando primer valor del axis 2
#primero accedemos a renglon

print(z[0,0])

z[0,0].sum()


[0.16835939 0.58558991 0.50808019]


1.262029483294758

In [16]:
#accediendo a primera columa de primera matriz, primero entramos a la primera matriz, luego usamos notacion usual
print(z[0][:,0])
z[0][:,0].sum()

[0.16835939 0.29730254 0.4472141  0.80804242 0.1990835 ]


1.9200019478509103

### explicacion de los axis

supongamos que tenemos un arreglo de 3 dimensiones:
```
[
[[1,1,1],[1,1,1],[1,1,1]]
[[1,1,1],[1,1,1],[1,1,1]]
[[1,1,1],[1,1,1],[1,1,1]]
]
```

level 0 es como si te andentrarse en un corchete, el más externo, entonces tendriamos para el caso de suma

```
[[1,1,1],[1,1,1],[1,1,1]]    +    [[1,1,1],[1,1,1],[1,1,1]]    +    [[1,1,1],[1,1,1],[1,1,1]]

```

es decir, suma de matrices. para el caso axis = 1, nos adentramos dos corchetes, y tenemos

```
[1,1,1],[1,1,1],[1,1,1]
[1,1,1],[1,1,1],[1,1,1]
[1,1,1],[1,1,1],[1,1,1]
```
es decir, sumas de vectores de la forma 

```
[1,1,1]    +    [1,1,1]    +    [1,1,1]
[1,1,1]    +    [1,1,1]    +    [1,1,1]
[1,1,1]    +    [1,1,1]    +    [1,1,1]
```

con lo que el resultado es como su sumaramos las columnas dentro de cada matriz, finalmete en caso axis 2, entramos aun más hasta los elementos 

```
[1,1,1]

```

es decir
```
1+1+1
```


### np.random.
al darle tab aparecen muchas distribuciones de probabilidad para generar numeros en arrays

In [38]:
np.random.

SyntaxError: invalid syntax (393120376.py, line 1)

In [5]:
# generar numeros aleatorios dandole una "semilla" es decir, esta se queda fija y determina siempre los mismos numeros aleatorios. 
#puedo ejecutar muchas veces siempre da la misma suma, porque son los mismos nuemros
np.random.seed(1993656)
z=np.random.rand(3,5,3)
z


array([[[0.69531348, 0.39815269, 0.81583854],
        [0.24431395, 0.41937184, 0.99741248],
        [0.80554691, 0.65674085, 0.10081847],
        [0.18275525, 0.37628301, 0.45360839],
        [0.20300837, 0.2668046 , 0.18872762]],

       [[0.84297983, 0.87224395, 0.98629208],
        [0.60786294, 0.98971772, 0.43269249],
        [0.47215026, 0.97211406, 0.60574734],
        [0.51085726, 0.34308179, 0.25105897],
        [0.95447361, 0.92082156, 0.9657179 ]],

       [[0.96275485, 0.94680387, 0.48885999],
        [0.99520028, 0.00489776, 0.88258104],
        [0.06617334, 0.17572993, 0.05293479],
        [0.90080387, 0.04975522, 0.30214646],
        [0.03935475, 0.18244245, 0.97720384]]])

In [31]:
#una vez usada se borra
r=np.random.rand(3,5,3)
r

array([[[0.16501311, 0.48360088, 0.68359307],
        [0.82032078, 0.31433263, 0.61463879],
        [0.60995105, 0.67882129, 0.10089668],
        [0.76494139, 0.28508584, 0.94911706],
        [0.21815399, 0.96713372, 0.06574138]],

       [[0.16835939, 0.58558991, 0.50808019],
        [0.29730254, 0.60933723, 0.52861179],
        [0.4472141 , 0.46125195, 0.17463062],
        [0.80804242, 0.667099  , 0.32215352],
        [0.1990835 , 0.59310502, 0.71421365]],

       [[0.01107267, 0.84556596, 0.26255542],
        [0.42663659, 0.63805456, 0.49837532],
        [0.47050994, 0.93584117, 0.96841341],
        [0.65113916, 0.49233799, 0.44594234],
        [0.08079271, 0.02901154, 0.25611287]]])