# Matrices sin np

In [2]:
row = [1,2,3]

In [3]:
col = [
    [1],
    [2],
    [3]
    ]

In [4]:
col

[[1], [2], [3]]

In [5]:
Matriz = [[1,2,3],[1,2,3],[1,2,3]]

In [6]:
#para acceder
Matriz[0][0]

1

Sin embargo es engorroso y el formato no se parece en nada al de matrices, para ello es mejor usar numpy

# Numpy

In [7]:
import numpy as np
M = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [8]:
M = np.array([[1,2,3],[1,2,3],[1,2,3]],dtype = float)

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.shape(M)

(3, 3)

In [12]:
## Operaciones matricez
A=np.zeros((2,2))
B=np.ones((2,2))
C=np.array([[1,2],[2,3]])

In [13]:
#suma
A+B

array([[1., 1.],
       [1., 1.]])

In [14]:
#porducto de matricez
A.dot(B)

array([[0., 0.],
       [0., 0.]])

In [15]:
# transpuesta
A.transpose()

array([[0., 0.],
       [0., 0.]])

In [16]:
A.trace() #traza amtriz

0.0

## np.linalg. 
dar tab para ver propieades de algebra lineal y matrices.

In [17]:
np.linalg.matrix_rank(C)

2

In [18]:
np.linalg.matrix_power(C,2)

array([[ 5,  8],
       [ 8, 13]])

In [19]:
np.linalg.det(C)

-1.0

In [20]:
np.linalg.inv(C)

array([[-3.,  2.],
       [ 2., -1.]])

In [21]:
np.linalg.inv(C).dot(C) #propiedad de inversa

array([[1., 0.],
       [0., 1.]])