# comparar con R

In [1]:
import pandas as pd
import math 
import numpy as np

cw = pd.read_table("../../data/datacrab.txt", sep = " ")
cw.head()

input  color  spine  width  satell  weight
0      1      3      3   28.3       8    3050
1      2      4      3   22.5       0    1550
2      3      2      1   26.0       9    2300
3      4      4      3   24.8       0    2100
4      5      4      3   26.0       4    2600

In [2]:
cw = cw.width
cw.head

<bound method NDFrame.head of 0      28.3
1      22.5
2      26.0
3      24.8
4      26.0
       ... 
168    26.1
169    29.0
170    28.0
171    27.0
172    24.5
Name: width, Length: 173, dtype: float64>

In [3]:
n = len(cw)
k1 = math.ceil(math.sqrt(n))

k2 = math.ceil(1 + math.log2(n))

k3 = 3.5 * np.std(cw) * pow(n,-(1/3))
# np.ptp(cw, axis = 0) sirve para clular rango directamente
k3 = math.ceil(  np.ptp(cw, axis = 0) /k3 )

k4 = 2 * ( np.percentile(cw, 75) - np.percentile(cw, 25) ) * pow(n,-(1/3))
k4 = math.ceil(  np.ptp(cw, axis = 0) /k4 )


print(k1,k2,k3,k4)


14 9 10 13


In [4]:
# amplitud, ejemplo con k3
z = np.ptp(cw, axis = 0) / k3
y = math.ceil(z* 10 ** 1)
y = y * 10 ** -1
if y == z :
    A = z + 10 ** -1
A = y

In [5]:
# ejemplo intervalos
L1 = cw.min() - 1 / 2 * 10 ** -1
L = L1 + A * np.arange(0,11)
L

array([20.95, 22.25, 23.55, 24.85, 26.15, 27.45, 28.75, 30.05, 31.35,
       32.65, 33.95])

In [6]:
# ejemplo  Etiquetas
X1 = ( L[0] + L[1]) /2 
X = X1 + A * np.arange(0,10)
X



array([21.6, 22.9, 24.2, 25.5, 26.8, 28.1, 29.4, 30.7, 32. , 33.3])

In [7]:
# forma alt
X = (L[0:(len(L)-1)] + L[1:(len(L))] ) / 2
X

array([21.6, 22.9, 24.2, 25.5, 26.8, 28.1, 29.4, 30.7, 32. , 33.3])